# Jekyll settings

title: Jeff Alessandrelli
author: Jeff Alessandrelli
description: >- # this means to ignore newlines until "baseurl:"
  Poetry.
baseurl: "" # e.g. /books
url: "https://jeffalessandrelli.net" # hostname and protocol
tumblr_url: "https://jeffalessandrelli.tumblr.com/"
instagram_url: "https://www.instagram.com/jalessandrelli/"
logo: "/images/bg_stars.gif"
social:
  name: Jeff Alessandrelli
  links:
    - https://jeffalessandrelli.tumblr.com
    - https://www.instagram.com/jalessandrelli/
google_analytics: "UA-113483194-1"
google_tag_manager: "GTM-5ZMTC37"

# Build settings:

markdown: kramdown
kramdown:
  auto_ids: false

sass:
  # sass_dir: assets/_sass
  # style: compressed
  # add_charset: true

plugins:
  - jekyll-tidy

# Content-editor settings--prose.io:

prose:
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - _config.yml
    - .gitignore
    - 404.html
    - android-chrome*
    - apple-touch-icon*
    - browserconfig.xml
    - CNAME
    - favicon*
    - Gemfile*
    - index.md
    - mstile*
    - README.md
    - robots.txt
    - site.webmanifest
    - sitemap.xml

# Exclude from processing:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
